### ISSUE TITLE
OnClose and OnCode not called

### ISSUE THREAD

**Issue by cristinaITdeveloper** [kgoedecke/react-oauth-popup#6] opened 2018-12-27 16:21 UTC
I use this oauth-popup for google calendar connection, passing the authUrl of google.
I obtain the code, but the OnCode and OnClose functions are not called.

**Comment by bionicvapourboy** [comment] 2019-03-21 16:38
`OnClose` has inconsistent behavior because is related to the `onbeforeunload` external window event that isn't fired (at least on current chrome version).

`OnCode` to be triggered need a parameter to be set in the popup url: `code`:

```
const params = new URL(this.externalWindow.location).searchParams;
        const code = params.get('access_token');
        if (!code) {
          return;
        }
```

As standard OAUTH2 auth payload returned does not contains a "code" attribute (by default we'll have `access_token`, `token_type`, `refresh_token`, `expires_in`, `expires_at`), `onCode` is never called.

**Comment by deveshlashkari** [comment] 2020-09-22 10:21
Is the issue resolved ??

**Comment by kgoedecke** [comment] 2020-10-05 20:33
@deveshlashkari I might have a fix. Can you help me to test it?

**Comment by kgoedecke** [comment] 2020-10-05 22:24
@bionicvapourboy @cristinaITdeveloper @deveshlashkari I've just released v1.0.0

Can you test if the issue is resolved on your end?

**Comment by blieb** [comment] 2020-10-05 22:25
> @deveshlashkari I might have a fix. Can you help me to test it?

I've had the same in safari. but I'm not allowed to read `this.externalWindow.location` when the popup is another domain. so when oauth is on another domain it breaks. So I've rebuild it to the callback url sends a message back to the main window.

**Comment by kgoedecke** [comment] 2020-10-05 22:27
@blieb I'd say that is expected behavior. The oAuth popup should redirect you to your own domain with the code in the url. Where are you being redirected to?

**Comment by kgoedecke** [comment] 2020-10-05 22:27
@blieb I've also just released v1.0.0 please make sure you're on the latest version.

**Comment by kgoedecke** [comment] 2020-10-07 23:02
also @bionicvapourboy please be aware that there are different types of oAuth flows:
- authorization code flow
- implicit grant flow

This library only supports the authorization code flow.

See: https://www.aha.io/api/oauth2
And: https://aaronparecki.com/oauth-2-simplified/#web-server-apps

**Comment by kgoedecke** [comment] 2020-11-03 13:28
Closing this for now since the issue at least on my end is resolved.

**Closed by kgoedecke** 2020-11-03 13:28 UTC
